# -*- coding: utf-8 -*-
"""Assignment 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f_xFvqU7jC4ofOzSFRnViw22Ipi6rEZn
"""

x=int(input("Enter 1 st input"))
y=int(input("Enter 2 nd input"))
print(x**y) # X to the power y